[build]
    publish = "public"
    command = "hugo --gc --minify -t -v -b"

[build.environment]
    HUGO_VERSION = "0.84.1"

[functions]
  directory = "functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200