[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.87.0"

[functions]
  directory = "functions"
# prevents havarotjs.prototype.trasnliterate from being overwritten
[functions.hebraiskTranslitteration]
  external_node_modules = ["hebraisk-translitteration"]
[functions.hebreiskaTranslitteration]
  external_node_modules = ["hebreiska-translitteration"]
[functions.umschrift]
  external_node_modules = ["umschrift"]
[functions.metagraphi]
  external_node_modules = ["metagraphi"]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "hugo"